language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel

  - docker tag udagram-api-feed:1.0.0 badex360/udagram-api-feed:1.0.0
  - docker tag udagram-api-user:1.0.0 badex360/udagram-api-user:1.0.0
  - docker tag udagram-frontend:1.0.0 badex360/udagram-frontend:1.0.0
  - docker tag reverseproxy:1.0.0 badex360/reverseproxy:1.0.0
  

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push badex360/udagram-api-feed:1.0.0
  - docker push badex360/udagram-api-user:1.0.0
  - docker push badex360/udagram-frontend:1.0.0
  - docker push badex360/reverseproxy:1.0.0